[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; img-src 'self' data: blob: https:; font-src 'self' https://fonts.gstatic.com data:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' https://cdnjs.cloudflare.com https://www.ratufa.io https://n1.ratufa.io; connect-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://www.ratufa.io https://n1.ratufa.io; frame-src https://www.ratufa.io https://n1.ratufa.io; form-action 'self' https://www.ratufa.io https://n1.ratufa.io; manifest-src 'self'; worker-src 'self' blob:; upgrade-insecure-requests"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Resource-Policy = "same-origin"
    Origin-Agent-Cluster = "?1"
    Permissions-Policy = "accelerometer=(), ambient-light-sensor=(), autoplay=(), camera=(), display-capture=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=(), xr-spatial-tracking=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-Permitted-Cross-Domain-Policies = "none"
